[2025-03-21T13:24:49.649+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transactions_pipeline.detect_fraud_batch_20250321_131702 manual__2025-03-21T13:22:01.068828+00:00 [queued]>
[2025-03-21T13:24:49.724+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transactions_pipeline.detect_fraud_batch_20250321_131702 manual__2025-03-21T13:22:01.068828+00:00 [queued]>
[2025-03-21T13:24:49.725+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-03-21T13:24:49.865+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): detect_fraud_batch_20250321_131702> on 2025-03-21 13:22:01.068828+00:00
[2025-03-21T13:24:49.910+0000] {standard_task_runner.py:57} INFO - Started process 1285 to run task
[2025-03-21T13:24:49.913+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'transactions_pipeline', 'detect_fraud_batch_20250321_131702', 'manual__2025-03-21T13:22:01.068828+00:00', '--job-id', '608', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_pipeline.py', '--cfg-path', '/tmp/tmpf_o6lq3f']
[2025-03-21T13:24:49.924+0000] {standard_task_runner.py:85} INFO - Job 608: Subtask detect_fraud_batch_20250321_131702
[2025-03-21T13:24:50.183+0000] {task_command.py:415} INFO - Running <TaskInstance: transactions_pipeline.detect_fraud_batch_20250321_131702 manual__2025-03-21T13:22:01.068828+00:00 [running]> on host 1b7c3466167a
[2025-03-21T13:24:50.607+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='rabiizahnoune7@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='transactions_pipeline' AIRFLOW_CTX_TASK_ID='detect_fraud_batch_20250321_131702' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T13:22:01.068828+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-21T13:22:01.068828+00:00'
[2025-03-21T13:24:50.614+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-21T13:24:50.618+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            docker exec hive spark-submit --master spark://localhost:7077 /hive/scripts/detect_fraud.py "batch_20250321_131702"\n            ']
[2025-03-21T13:24:50.701+0000] {subprocess.py:86} INFO - Output:
[2025-03-21T13:26:00.140+0000] {subprocess.py:93} INFO - 25/03/21 13:26:00 INFO SparkContext: Running Spark version 3.5.0
[2025-03-21T13:26:00.142+0000] {subprocess.py:93} INFO - 25/03/21 13:26:00 INFO SparkContext: OS info Linux, 5.15.167.4-microsoft-standard-WSL2, amd64
[2025-03-21T13:26:00.234+0000] {subprocess.py:93} INFO - 25/03/21 13:26:00 INFO SparkContext: Java version 1.8.0_342
[2025-03-21T13:26:04.439+0000] {subprocess.py:93} INFO - 25/03/21 13:26:04 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-21T13:26:06.516+0000] {subprocess.py:93} INFO - 25/03/21 13:26:06 INFO ResourceUtils: ==============================================================
[2025-03-21T13:26:06.521+0000] {subprocess.py:93} INFO - 25/03/21 13:26:06 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-03-21T13:26:06.522+0000] {subprocess.py:93} INFO - 25/03/21 13:26:06 INFO ResourceUtils: ==============================================================
[2025-03-21T13:26:06.612+0000] {subprocess.py:93} INFO - 25/03/21 13:26:06 INFO SparkContext: Submitted application: FraudDetection
[2025-03-21T13:26:07.218+0000] {subprocess.py:93} INFO - 25/03/21 13:26:07 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-03-21T13:26:07.712+0000] {subprocess.py:93} INFO - 25/03/21 13:26:07 INFO ResourceProfile: Limiting resource is cpu
[2025-03-21T13:26:07.722+0000] {subprocess.py:93} INFO - 25/03/21 13:26:07 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-03-21T13:26:09.109+0000] {subprocess.py:93} INFO - 25/03/21 13:26:09 INFO SecurityManager: Changing view acls to: root
[2025-03-21T13:26:09.113+0000] {subprocess.py:93} INFO - 25/03/21 13:26:09 INFO SecurityManager: Changing modify acls to: root
[2025-03-21T13:26:09.125+0000] {subprocess.py:93} INFO - 25/03/21 13:26:09 INFO SecurityManager: Changing view acls groups to:
[2025-03-21T13:26:09.127+0000] {subprocess.py:93} INFO - 25/03/21 13:26:09 INFO SecurityManager: Changing modify acls groups to:
[2025-03-21T13:26:09.216+0000] {subprocess.py:93} INFO - 25/03/21 13:26:09 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: root; groups with view permissions: EMPTY; users with modify permissions: root; groups with modify permissions: EMPTY
[2025-03-21T13:26:21.219+0000] {subprocess.py:93} INFO - 25/03/21 13:26:21 INFO Utils: Successfully started service 'sparkDriver' on port 45405.
[2025-03-21T13:26:22.728+0000] {subprocess.py:93} INFO - 25/03/21 13:26:22 INFO SparkEnv: Registering MapOutputTracker
[2025-03-21T13:26:24.426+0000] {subprocess.py:93} INFO - 25/03/21 13:26:24 INFO SparkEnv: Registering BlockManagerMaster
[2025-03-21T13:26:26.122+0000] {subprocess.py:93} INFO - 25/03/21 13:26:26 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-03-21T13:26:26.124+0000] {subprocess.py:93} INFO - 25/03/21 13:26:26 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-03-21T13:26:26.421+0000] {subprocess.py:93} INFO - 25/03/21 13:26:26 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-03-21T13:26:30.113+0000] {subprocess.py:93} INFO - 25/03/21 13:26:30 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-b971ca26-f949-4e55-a1f3-d016ecfc23fa
[2025-03-21T13:26:30.628+0000] {subprocess.py:93} INFO - 25/03/21 13:26:30 INFO MemoryStore: MemoryStore started with capacity 366.3 MiB
[2025-03-21T13:26:31.625+0000] {subprocess.py:93} INFO - 25/03/21 13:26:31 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-03-21T13:26:35.780+0000] {subprocess.py:93} INFO - 25/03/21 13:26:35 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-03-21T13:26:38.885+0000] {subprocess.py:93} INFO - 25/03/21 13:26:38 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2025-03-21T13:26:38.894+0000] {subprocess.py:93} INFO - 25/03/21 13:26:38 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2025-03-21T13:26:39.295+0000] {subprocess.py:93} INFO - 25/03/21 13:26:39 INFO Utils: Successfully started service 'SparkUI' on port 4042.
[2025-03-21T13:26:46.378+0000] {subprocess.py:93} INFO - 25/03/21 13:26:46 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://localhost:7077...
[2025-03-21T13:26:49.480+0000] {subprocess.py:93} INFO - 25/03/21 13:26:49 INFO TransportClientFactory: Successfully created connection to localhost/127.0.0.1:7077 after 1712 ms (0 ms spent in bootstraps)
[2025-03-21T13:27:01.194+0000] {subprocess.py:93} INFO - 25/03/21 13:27:01 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250321132700-0005
[2025-03-21T13:27:01.384+0000] {subprocess.py:93} INFO - 25/03/21 13:27:01 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 39993.
[2025-03-21T13:27:01.386+0000] {subprocess.py:93} INFO - 25/03/21 13:27:01 INFO NettyBlockTransferService: Server created on e3006a54eed1:39993
[2025-03-21T13:27:01.388+0000] {subprocess.py:93} INFO - 25/03/21 13:27:01 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-03-21T13:27:01.486+0000] {subprocess.py:93} INFO - 25/03/21 13:27:01 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, e3006a54eed1, 39993, None)
[2025-03-21T13:27:01.594+0000] {subprocess.py:93} INFO - 25/03/21 13:27:01 INFO BlockManagerMasterEndpoint: Registering block manager e3006a54eed1:39993 with 366.3 MiB RAM, BlockManagerId(driver, e3006a54eed1, 39993, None)
[2025-03-21T13:27:01.597+0000] {subprocess.py:93} INFO - 25/03/21 13:27:01 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, e3006a54eed1, 39993, None)
[2025-03-21T13:27:01.603+0000] {subprocess.py:93} INFO - 25/03/21 13:27:01 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, e3006a54eed1, 39993, None)
[2025-03-21T13:27:15.423+0000] {job.py:219} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/jobs/job.py", line 190, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-03-21T13:27:27.175+0000] {subprocess.py:93} INFO - 25/03/21 13:27:26 INFO AsyncEventQueue: Process of event SparkListenerResourceProfileAdded(Profile: id = 0, executor resources: memory -> name: memory, amount: 1024, script: , vendor: ,offHeap -> name: offHeap, amount: 0, script: , vendor: , task resources: cpus -> name: cpus, amount: 1.0) by listener HeartbeatReceiver took 12.827023385s.
[2025-03-21T13:27:27.244+0000] {subprocess.py:93} INFO - 25/03/21 13:27:27 INFO AsyncEventQueue: Process of event SparkListenerResourceProfileAdded(Profile: id = 0, executor resources: memory -> name: memory, amount: 1024, script: , vendor: ,offHeap -> name: offHeap, amount: 0, script: , vendor: , task resources: cpus -> name: cpus, amount: 1.0) by listener AppStatusListener took 13.325997478s.
[2025-03-21T13:27:29.738+0000] {subprocess.py:93} INFO - 25/03/21 13:27:29 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-03-21T13:27:34.903+0000] {subprocess.py:93} INFO - Spark version: 3.5.0
[2025-03-21T13:27:36.721+0000] {subprocess.py:93} INFO - 25/03/21 13:27:36 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-03-21T13:27:38.505+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to removed. Terminating instance.
[2025-03-21T13:27:38.548+0000] {process_utils.py:131} INFO - Sending 15 to group 1285. PIDs of all processes in the group: [1310, 1323, 1285]
[2025-03-21T13:27:38.554+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 1285
[2025-03-21T13:27:38.556+0000] {taskinstance.py:1630} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-03-21T13:27:38.557+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-03-21T13:27:38.867+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1285, status='terminated', exitcode=0, started='13:24:49') (1285) terminated with exit code 0
[2025-03-21T13:27:38.877+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1323, status='terminated', started='13:24:49') (1323) terminated with exit code None
[2025-03-21T13:27:38.880+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1310, status='terminated', started='13:24:49') (1310) terminated with exit code None
