[2025-03-19T17:26:15.256+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transactions_pipeline.copy_to_hdfs scheduled__2025-03-19T17:21:13.237024+00:00 [queued]>
[2025-03-19T17:26:15.268+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transactions_pipeline.copy_to_hdfs scheduled__2025-03-19T17:21:13.237024+00:00 [queued]>
[2025-03-19T17:26:15.269+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-03-19T17:26:15.288+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): copy_to_hdfs> on 2025-03-19 17:21:13.237024+00:00
[2025-03-19T17:26:15.294+0000] {standard_task_runner.py:57} INFO - Started process 533 to run task
[2025-03-19T17:26:15.297+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'transactions_pipeline', 'copy_to_hdfs', 'scheduled__2025-03-19T17:21:13.237024+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_pipeline.py', '--cfg-path', '/tmp/tmpq3mem7df']
[2025-03-19T17:26:15.302+0000] {standard_task_runner.py:85} INFO - Job 82: Subtask copy_to_hdfs
[2025-03-19T17:26:15.366+0000] {task_command.py:415} INFO - Running <TaskInstance: transactions_pipeline.copy_to_hdfs scheduled__2025-03-19T17:21:13.237024+00:00 [running]> on host 347688f31140
[2025-03-19T17:26:15.487+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='transactions_pipeline' AIRFLOW_CTX_TASK_ID='copy_to_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-03-19T17:21:13.237024+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-19T17:21:13.237024+00:00'
[2025-03-19T17:26:15.490+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-19T17:26:15.491+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec hive hdfs dfs -mkdir -p /data/transactions/transactions_batch_0 && docker exec hive hdfs dfs -put -f /data/transactions/transactions_batch_0.parquet /data/transactions/transactions_batch_0/']
[2025-03-19T17:26:15.504+0000] {subprocess.py:86} INFO - Output:
[2025-03-19T17:26:20.984+0000] {subprocess.py:93} INFO - put: `/data/transactions/transactions_batch_0/': No such file or directory: `hdfs://localhost:9000/data/transactions/transactions_batch_0'
[2025-03-19T17:26:21.443+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-03-19T17:26:21.459+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-19T17:26:21.464+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=transactions_pipeline, task_id=copy_to_hdfs, execution_date=20250319T172113, start_date=20250319T172615, end_date=20250319T172621
[2025-03-19T17:26:21.489+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 82 for task copy_to_hdfs (Bash command failed. The command returned a non-zero exit code 1.; 533)
[2025-03-19T17:26:21.505+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-19T17:26:21.531+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
