[2025-03-19T22:38:41.570+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transactions_pipeline.copy_to_hdfs manual__2025-03-19T22:38:37.478357+00:00 [queued]>
[2025-03-19T22:38:41.582+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transactions_pipeline.copy_to_hdfs manual__2025-03-19T22:38:37.478357+00:00 [queued]>
[2025-03-19T22:38:41.583+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-03-19T22:38:41.604+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): copy_to_hdfs> on 2025-03-19 22:38:37.478357+00:00
[2025-03-19T22:38:41.610+0000] {standard_task_runner.py:57} INFO - Started process 201 to run task
[2025-03-19T22:38:41.614+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'transactions_pipeline', 'copy_to_hdfs', 'manual__2025-03-19T22:38:37.478357+00:00', '--job-id', '202', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_pipeline.py', '--cfg-path', '/tmp/tmpligh8_4c']
[2025-03-19T22:38:41.617+0000] {standard_task_runner.py:85} INFO - Job 202: Subtask copy_to_hdfs
[2025-03-19T22:38:41.697+0000] {task_command.py:415} INFO - Running <TaskInstance: transactions_pipeline.copy_to_hdfs manual__2025-03-19T22:38:37.478357+00:00 [running]> on host ea3c2858f428
[2025-03-19T22:38:41.865+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='transactions_pipeline' AIRFLOW_CTX_TASK_ID='copy_to_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-03-19T22:38:37.478357+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-19T22:38:37.478357+00:00'
[2025-03-19T22:38:41.867+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-19T22:38:41.869+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec hive hdfs dfs -mkdir -p /data/transactions/transactions_batch_0 && docker exec hive hdfs dfs -put -f /data/transactions/transactions_batch_0.parquet /data/transactions/transactions_batch_0/']
[2025-03-19T22:38:41.885+0000] {subprocess.py:86} INFO - Output:
[2025-03-19T22:38:46.958+0000] {subprocess.py:93} INFO - 2025-03-19 22:38:46,951 WARN hdfs.DataStreamer: DataStreamer Exception
[2025-03-19T22:38:46.960+0000] {subprocess.py:93} INFO - org.apache.hadoop.ipc.RemoteException(java.io.IOException): File /data/transactions/transactions_batch_0/transactions_batch_0.parquet._COPYING_ could only be written to 0 of the 1 minReplication nodes. There are 0 datanode(s) running and no node(s) are excluded in this operation.
[2025-03-19T22:38:46.963+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.blockmanagement.BlockManager.chooseTarget4NewBlock(BlockManager.java:2116)
[2025-03-19T22:38:46.964+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.chooseTargetForNewBlock(FSDirWriteFileOp.java:287)
[2025-03-19T22:38:46.965+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:2688)
[2025-03-19T22:38:46.965+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:875)
[2025-03-19T22:38:46.966+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:559)
[2025-03-19T22:38:46.967+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
[2025-03-19T22:38:46.967+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
[2025-03-19T22:38:46.968+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
[2025-03-19T22:38:46.969+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:869)
[2025-03-19T22:38:46.970+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:815)
[2025-03-19T22:38:46.971+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-03-19T22:38:46.972+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-03-19T22:38:46.972+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1682)
[2025-03-19T22:38:46.973+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2675)
[2025-03-19T22:38:46.974+0000] {subprocess.py:93} INFO - 
[2025-03-19T22:38:46.974+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1491)
[2025-03-19T22:38:46.975+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1437)
[2025-03-19T22:38:46.976+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1347)
[2025-03-19T22:38:46.976+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:228)
[2025-03-19T22:38:46.977+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116)
[2025-03-19T22:38:46.978+0000] {subprocess.py:93} INFO - 	at com.sun.proxy.$Proxy11.addBlock(Unknown Source)
[2025-03-19T22:38:46.978+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.addBlock(ClientNamenodeProtocolTranslatorPB.java:504)
[2025-03-19T22:38:46.979+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-03-19T22:38:46.979+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-03-19T22:38:46.980+0000] {subprocess.py:93} INFO - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-03-19T22:38:46.980+0000] {subprocess.py:93} INFO - 	at java.lang.reflect.Method.invoke(Method.java:498)
[2025-03-19T22:38:46.981+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-03-19T22:38:46.981+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-03-19T22:38:46.982+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-03-19T22:38:46.982+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-03-19T22:38:46.983+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-03-19T22:38:46.983+0000] {subprocess.py:93} INFO - 	at com.sun.proxy.$Proxy12.addBlock(Unknown Source)
[2025-03-19T22:38:46.984+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSOutputStream.addBlock(DFSOutputStream.java:1078)
[2025-03-19T22:38:46.984+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DataStreamer.locateFollowingBlock(DataStreamer.java:1865)
[2025-03-19T22:38:46.985+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DataStreamer.nextBlockOutputStream(DataStreamer.java:1668)
[2025-03-19T22:38:46.985+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:716)
[2025-03-19T22:38:46.997+0000] {subprocess.py:93} INFO - put: File /data/transactions/transactions_batch_0/transactions_batch_0.parquet._COPYING_ could only be written to 0 of the 1 minReplication nodes. There are 0 datanode(s) running and no node(s) are excluded in this operation.
[2025-03-19T22:38:47.457+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-03-19T22:38:47.478+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-19T22:38:47.485+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=transactions_pipeline, task_id=copy_to_hdfs, execution_date=20250319T223837, start_date=20250319T223841, end_date=20250319T223847
[2025-03-19T22:38:47.514+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 202 for task copy_to_hdfs (Bash command failed. The command returned a non-zero exit code 1.; 201)
[2025-03-19T22:38:47.567+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-19T22:38:47.613+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
