[2025-03-20T09:43:27.682+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transactions_pipeline.copy_to_hdfs scheduled__2025-03-20T05:54:58.253415+00:00 [queued]>
[2025-03-20T09:43:27.731+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transactions_pipeline.copy_to_hdfs scheduled__2025-03-20T05:54:58.253415+00:00 [queued]>
[2025-03-20T09:43:27.732+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-03-20T09:43:27.790+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): copy_to_hdfs> on 2025-03-20 05:54:58.253415+00:00
[2025-03-20T09:43:27.822+0000] {standard_task_runner.py:57} INFO - Started process 4239 to run task
[2025-03-20T09:43:27.822+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'transactions_pipeline', 'copy_to_hdfs', 'scheduled__2025-03-20T05:54:58.253415+00:00', '--job-id', '242', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_pipeline.py', '--cfg-path', '/tmp/tmpaf53atrn']
[2025-03-20T09:43:27.838+0000] {standard_task_runner.py:85} INFO - Job 242: Subtask copy_to_hdfs
[2025-03-20T09:43:28.069+0000] {task_command.py:415} INFO - Running <TaskInstance: transactions_pipeline.copy_to_hdfs scheduled__2025-03-20T05:54:58.253415+00:00 [running]> on host 87980e846a97
[2025-03-20T09:43:28.545+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='transactions_pipeline' AIRFLOW_CTX_TASK_ID='copy_to_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-03-20T05:54:58.253415+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-20T05:54:58.253415+00:00'
[2025-03-20T09:43:28.552+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-20T09:43:28.555+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec hive hdfs dfs -mkdir -p /data/transactions/transactions_batch_0 && docker exec hive hdfs dfs -put -f /data/transactions/transactions_batch_0.parquet /data/transactions/transactions_batch_0/']
[2025-03-20T09:43:28.586+0000] {subprocess.py:86} INFO - Output:
[2025-03-20T09:43:37.121+0000] {subprocess.py:93} INFO - 2025-03-20 09:43:37,114 WARN hdfs.DataStreamer: DataStreamer Exception
[2025-03-20T09:43:37.123+0000] {subprocess.py:93} INFO - java.io.FileNotFoundException: File does not exist: /data/transactions/transactions_batch_0/transactions_batch_0.parquet._COPYING_ (inode 16458) Holder DFSClient_NONMAPREDUCE_674257371_1 does not have any open files.
[2025-03-20T09:43:37.124+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkLease(FSNamesystem.java:2797)
[2025-03-20T09:43:37.124+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.analyzeFileState(FSDirWriteFileOp.java:597)
[2025-03-20T09:43:37.125+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.validateAddBlock(FSDirWriteFileOp.java:172)
[2025-03-20T09:43:37.125+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:2676)
[2025-03-20T09:43:37.126+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:875)
[2025-03-20T09:43:37.126+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:559)
[2025-03-20T09:43:37.127+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
[2025-03-20T09:43:37.127+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
[2025-03-20T09:43:37.127+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
[2025-03-20T09:43:37.128+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:869)
[2025-03-20T09:43:37.128+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:815)
[2025-03-20T09:43:37.129+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-03-20T09:43:37.129+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-03-20T09:43:37.129+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1682)
[2025-03-20T09:43:37.130+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2675)
[2025-03-20T09:43:37.130+0000] {subprocess.py:93} INFO - 
[2025-03-20T09:43:37.131+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-03-20T09:43:37.131+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2025-03-20T09:43:37.131+0000] {subprocess.py:93} INFO - 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-03-20T09:43:37.132+0000] {subprocess.py:93} INFO - 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[2025-03-20T09:43:37.132+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:121)
[2025-03-20T09:43:37.132+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:88)
[2025-03-20T09:43:37.133+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSOutputStream.addBlock(DFSOutputStream.java:1081)
[2025-03-20T09:43:37.133+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DataStreamer.locateFollowingBlock(DataStreamer.java:1865)
[2025-03-20T09:43:37.134+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DataStreamer.nextBlockOutputStream(DataStreamer.java:1668)
[2025-03-20T09:43:37.134+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DataStreamer.run(DataStreamer.java:716)
[2025-03-20T09:43:37.135+0000] {subprocess.py:93} INFO - Caused by: org.apache.hadoop.ipc.RemoteException(java.io.FileNotFoundException): File does not exist: /data/transactions/transactions_batch_0/transactions_batch_0.parquet._COPYING_ (inode 16458) Holder DFSClient_NONMAPREDUCE_674257371_1 does not have any open files.
[2025-03-20T09:43:37.135+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.checkLease(FSNamesystem.java:2797)
[2025-03-20T09:43:37.135+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.analyzeFileState(FSDirWriteFileOp.java:597)
[2025-03-20T09:43:37.136+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.validateAddBlock(FSDirWriteFileOp.java:172)
[2025-03-20T09:43:37.136+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:2676)
[2025-03-20T09:43:37.136+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:875)
[2025-03-20T09:43:37.137+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:559)
[2025-03-20T09:43:37.137+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
[2025-03-20T09:43:37.137+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:523)
[2025-03-20T09:43:37.137+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:991)
[2025-03-20T09:43:37.138+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:869)
[2025-03-20T09:43:37.138+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:815)
[2025-03-20T09:43:37.138+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-03-20T09:43:37.139+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-03-20T09:43:37.139+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1682)
[2025-03-20T09:43:37.139+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2675)
[2025-03-20T09:43:37.140+0000] {subprocess.py:93} INFO - 
[2025-03-20T09:43:37.140+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1491)
[2025-03-20T09:43:37.140+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1437)
[2025-03-20T09:43:37.141+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1347)
[2025-03-20T09:43:37.141+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:228)
[2025-03-20T09:43:37.141+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116)
[2025-03-20T09:43:37.141+0000] {subprocess.py:93} INFO - 	at com.sun.proxy.$Proxy11.addBlock(Unknown Source)
[2025-03-20T09:43:37.141+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.addBlock(ClientNamenodeProtocolTranslatorPB.java:504)
[2025-03-20T09:43:37.142+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-03-20T09:43:37.142+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-03-20T09:43:37.142+0000] {subprocess.py:93} INFO - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-03-20T09:43:37.142+0000] {subprocess.py:93} INFO - 	at java.lang.reflect.Method.invoke(Method.java:498)
[2025-03-20T09:43:37.142+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-03-20T09:43:37.143+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-03-20T09:43:37.143+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-03-20T09:43:37.143+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-03-20T09:43:37.143+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-03-20T09:43:37.143+0000] {subprocess.py:93} INFO - 	at com.sun.proxy.$Proxy12.addBlock(Unknown Source)
[2025-03-20T09:43:37.144+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSOutputStream.addBlock(DFSOutputStream.java:1078)
[2025-03-20T09:43:37.144+0000] {subprocess.py:93} INFO - 	... 3 more
[2025-03-20T09:43:37.144+0000] {subprocess.py:93} INFO - put: File does not exist: /data/transactions/transactions_batch_0/transactions_batch_0.parquet._COPYING_ (inode 16458) Holder DFSClient_NONMAPREDUCE_674257371_1 does not have any open files.
[2025-03-20T09:43:37.569+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-03-20T09:43:37.589+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-20T09:43:37.595+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=transactions_pipeline, task_id=copy_to_hdfs, execution_date=20250320T055458, start_date=20250320T094327, end_date=20250320T094337
[2025-03-20T09:43:37.613+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 242 for task copy_to_hdfs (Bash command failed. The command returned a non-zero exit code 1.; 4239)
[2025-03-20T09:43:37.651+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-20T09:43:37.675+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
