[2025-03-21T15:52:46.195+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transactions_pipeline.create_hive_table_batch_20250321_155012 scheduled__2025-03-21T15:44:27.968260+00:00 [queued]>
[2025-03-21T15:52:46.223+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transactions_pipeline.create_hive_table_batch_20250321_155012 scheduled__2025-03-21T15:44:27.968260+00:00 [queued]>
[2025-03-21T15:52:46.225+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-03-21T15:52:46.257+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): create_hive_table_batch_20250321_155012> on 2025-03-21 15:44:27.968260+00:00
[2025-03-21T15:52:46.270+0000] {standard_task_runner.py:57} INFO - Started process 293 to run task
[2025-03-21T15:52:46.277+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'transactions_pipeline', 'create_hive_table_batch_20250321_155012', 'scheduled__2025-03-21T15:44:27.968260+00:00', '--job-id', '849', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_pipeline.py', '--cfg-path', '/tmp/tmp7417kosw']
[2025-03-21T15:52:46.283+0000] {standard_task_runner.py:85} INFO - Job 849: Subtask create_hive_table_batch_20250321_155012
[2025-03-21T15:52:46.390+0000] {task_command.py:415} INFO - Running <TaskInstance: transactions_pipeline.create_hive_table_batch_20250321_155012 scheduled__2025-03-21T15:44:27.968260+00:00 [running]> on host 31abf5c063d1
[2025-03-21T15:52:46.559+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='transactions_pipeline' AIRFLOW_CTX_TASK_ID='create_hive_table_batch_20250321_155012' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T15:44:27.968260+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-21T15:44:27.968260+00:00'
[2025-03-21T15:52:46.562+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-21T15:52:46.564+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            docker exec hive beeline -u "jdbc:hive2://localhost:10000" --hiveconf hive.exec.dynamic.partition.mode=nonstrict -e "\n            CREATE EXTERNAL TABLE IF NOT EXISTS transactions (\n                transaction_id STRING,\n                date_time STRING,\n                amount DOUBLE,\n                currency STRING,\n                merchant_details STRING,\n                customer_id STRING,\n                transaction_type STRING,\n                location STRING\n            )\n            PARTITIONED BY (batch_id STRING)\n            STORED AS PARQUET;\n            ALTER TABLE transactions ADD IF NOT EXISTS PARTITION (batch_id=\'batch_20250321_155012\') LOCATION \'/data/transactions/transactions_batch_20250321_155012\';"\n            ']
[2025-03-21T15:52:46.584+0000] {subprocess.py:86} INFO - Output:
[2025-03-21T15:52:49.059+0000] {subprocess.py:93} INFO - SLF4J: Class path contains multiple SLF4J bindings.
[2025-03-21T15:52:49.060+0000] {subprocess.py:93} INFO - SLF4J: Found binding in [jar:file:/opt/hive/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[2025-03-21T15:52:49.061+0000] {subprocess.py:93} INFO - SLF4J: Found binding in [jar:file:/opt/hadoop/share/hadoop/common/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[2025-03-21T15:52:49.062+0000] {subprocess.py:93} INFO - SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
[2025-03-21T15:52:49.435+0000] {subprocess.py:93} INFO - SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
[2025-03-21T15:52:51.940+0000] {subprocess.py:93} INFO - Connecting to jdbc:hive2://localhost:10000
[2025-03-21T15:52:52.063+0000] {subprocess.py:93} INFO - 25/03/21 15:52:52 [main]: WARN jdbc.HiveConnection: Failed to connect to localhost:10000
[2025-03-21T15:52:52.076+0000] {subprocess.py:93} INFO - Could not open connection to the HS2 server. Please check the server URI and if the URI is correct, then ask the administrator to check the server status.
[2025-03-21T15:52:52.084+0000] {subprocess.py:93} INFO - Error: Could not open client transport with JDBC Uri: jdbc:hive2://localhost:10000: java.net.ConnectException: Connection refused (Connection refused) (state=08S01,code=0)
[2025-03-21T15:52:52.086+0000] {subprocess.py:93} INFO - Cannot run commands specified using -e. No current connection
[2025-03-21T15:52:52.137+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-03-21T15:52:52.158+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-21T15:52:52.166+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=transactions_pipeline, task_id=create_hive_table_batch_20250321_155012, execution_date=20250321T154427, start_date=20250321T155246, end_date=20250321T155252
[2025-03-21T15:52:52.180+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:206 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-03-21T15:52:52.465+0000] {fraud_detection_pipeline.py:50} ERROR - Failed to send Discord message: 400 - {"webhook_id": ["Value \"XXXXX\" is not snowflake."]}
[2025-03-21T15:52:52.490+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 849 for task create_hive_table_batch_20250321_155012 (Bash command failed. The command returned a non-zero exit code 1.; 293)
[2025-03-21T15:52:52.540+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-21T15:52:52.568+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
