[2025-03-21T20:39:20.332+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: external_customer_pipeline.fetch_external_data manual__2025-03-21T20:39:00.817956+00:00 [queued]>
[2025-03-21T20:39:20.351+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: external_customer_pipeline.fetch_external_data manual__2025-03-21T20:39:00.817956+00:00 [queued]>
[2025-03-21T20:39:20.352+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 3
[2025-03-21T20:39:18.560+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): fetch_external_data> on 2025-03-21 20:39:00.817956+00:00
[2025-03-21T20:39:18.569+0000] {standard_task_runner.py:57} INFO - Started process 3031 to run task
[2025-03-21T20:39:18.576+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'external_customer_pipeline', 'fetch_external_data', 'manual__2025-03-21T20:39:00.817956+00:00', '--job-id', '921', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_batch.py', '--cfg-path', '/tmp/tmp74achj8i']
[2025-03-21T20:39:18.580+0000] {standard_task_runner.py:85} INFO - Job 921: Subtask fetch_external_data
[2025-03-21T20:39:18.657+0000] {task_command.py:415} INFO - Running <TaskInstance: external_customer_pipeline.fetch_external_data manual__2025-03-21T20:39:00.817956+00:00 [running]> on host 4f421949e8a6
[2025-03-21T20:39:18.772+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='external_customer_pipeline' AIRFLOW_CTX_TASK_ID='fetch_external_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T20:39:00.817956+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-21T20:39:00.817956+00:00'
[2025-03-21T20:39:18.791+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:314 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-03-21T20:39:19.191+0000] {pipeline_batch.py:48} INFO - Discord message sent successfully
[2025-03-21T20:39:19.197+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-03-21T20:39:19.210+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=external_customer_pipeline, task_id=fetch_external_data, execution_date=20250321T203900, start_date=20250321T203920, end_date=20250321T203919
[2025-03-21T20:39:19.215+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:206 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-03-21T20:39:19.637+0000] {pipeline_batch.py:48} INFO - Discord message sent successfully
[2025-03-21T20:39:19.688+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-21T20:39:19.738+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
