[2025-03-21T20:24:59.720+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: external_customer_pipeline.store_external_data_to_hdfs_and_hive manual__2025-03-21T20:24:34.002999+00:00 [queued]>
[2025-03-21T20:24:59.734+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: external_customer_pipeline.store_external_data_to_hdfs_and_hive manual__2025-03-21T20:24:34.002999+00:00 [queued]>
[2025-03-21T20:24:59.736+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 3
[2025-03-21T20:24:59.756+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): store_external_data_to_hdfs_and_hive> on 2025-03-21 20:24:34.002999+00:00
[2025-03-21T20:24:59.764+0000] {standard_task_runner.py:57} INFO - Started process 1996 to run task
[2025-03-21T20:24:59.769+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'external_customer_pipeline', 'store_external_data_to_hdfs_and_hive', 'manual__2025-03-21T20:24:34.002999+00:00', '--job-id', '903', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_batch.py', '--cfg-path', '/tmp/tmp4ngwu5o3']
[2025-03-21T20:24:59.773+0000] {standard_task_runner.py:85} INFO - Job 903: Subtask store_external_data_to_hdfs_and_hive
[2025-03-21T20:24:59.833+0000] {task_command.py:415} INFO - Running <TaskInstance: external_customer_pipeline.store_external_data_to_hdfs_and_hive manual__2025-03-21T20:24:34.002999+00:00 [running]> on host 4f421949e8a6
[2025-03-21T20:24:59.942+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='external_customer_pipeline' AIRFLOW_CTX_TASK_ID='store_external_data_to_hdfs_and_hive' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T20:24:34.002999+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-21T20:24:34.002999+00:00'
[2025-03-21T20:25:02.813+0000] {pipeline_batch.py:169} INFO - HDFS put command output: 
[2025-03-21T20:25:08.467+0000] {pipeline_batch.py:44} INFO - Discord message sent successfully
[2025-03-21T20:25:08.470+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pipeline_batch.py", line 188, in store_external_data_to_hdfs_and_hive
    subprocess.run(create_table_cmd, shell=True, check=True)
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '
            docker exec hive beeline -u "jdbc:hive2://localhost:10000" --hiveconf hive.exec.dynamic.partition.mode=nonstrict -e "
            CREATE EXTERNAL TABLE IF NOT EXISTS external_data (
                blacklist_info ARRAY<STRING>,
                credit_scores MAP<STRING, INT>,
                fraud_reports MAP<STRING, INT>
            )
            PARTITIONED BY (batch_id STRING)
            STORED AS JSONFILE
            LOCATION '/data/external_data';
            ALTER TABLE external_data ADD IF NOT EXISTS PARTITION (batch_id='20250321_202434') LOCATION '/data/external_data/external_data_20250321_202434.json';"
            ' returned non-zero exit status 1.
[2025-03-21T20:25:08.492+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=external_customer_pipeline, task_id=store_external_data_to_hdfs_and_hive, execution_date=20250321T202434, start_date=20250321T202459, end_date=20250321T202508
[2025-03-21T20:25:08.522+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 903 for task store_external_data_to_hdfs_and_hive (Command '
            docker exec hive beeline -u "jdbc:hive2://localhost:10000" --hiveconf hive.exec.dynamic.partition.mode=nonstrict -e "
            CREATE EXTERNAL TABLE IF NOT EXISTS external_data (
                blacklist_info ARRAY<STRING>,
                credit_scores MAP<STRING, INT>,
                fraud_reports MAP<STRING, INT>
            )
            PARTITIONED BY (batch_id STRING)
            STORED AS JSONFILE
            LOCATION '/data/external_data';
            ALTER TABLE external_data ADD IF NOT EXISTS PARTITION (batch_id='20250321_202434') LOCATION '/data/external_data/external_data_20250321_202434.json';"
            ' returned non-zero exit status 1.; 1996)
[2025-03-21T20:25:08.563+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-21T20:25:08.593+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
