[2025-03-19T22:52:52.623+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transactions_pipeline.detect_fraud manual__2025-03-19T22:52:31.955469+00:00 [queued]>
[2025-03-19T22:52:52.645+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transactions_pipeline.detect_fraud manual__2025-03-19T22:52:31.955469+00:00 [queued]>
[2025-03-19T22:52:52.647+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-03-19T22:52:52.688+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): detect_fraud> on 2025-03-19 22:52:31.955469+00:00
[2025-03-19T22:52:52.699+0000] {standard_task_runner.py:57} INFO - Started process 249 to run task
[2025-03-19T22:52:52.708+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'transactions_pipeline', 'detect_fraud', 'manual__2025-03-19T22:52:31.955469+00:00', '--job-id', '211', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_pipeline.py', '--cfg-path', '/tmp/tmpr930ldou']
[2025-03-19T22:52:52.714+0000] {standard_task_runner.py:85} INFO - Job 211: Subtask detect_fraud
[2025-03-19T22:52:52.792+0000] {task_command.py:415} INFO - Running <TaskInstance: transactions_pipeline.detect_fraud manual__2025-03-19T22:52:31.955469+00:00 [running]> on host 87980e846a97
[2025-03-19T22:52:52.919+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='transactions_pipeline' AIRFLOW_CTX_TASK_ID='detect_fraud' AIRFLOW_CTX_EXECUTION_DATE='2025-03-19T22:52:31.955469+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-19T22:52:31.955469+00:00'
[2025-03-19T22:52:52.921+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-19T22:52:52.922+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n    docker exec hive beeline -u "jdbc:hive2://localhost:10000" --hiveconf hive.exec.dynamic.partition.mode=nonstrict -e"\n    CREATE TABLE IF NOT EXISTS fraud_detections (\n        transaction_id STRING,\n        date_time STRING,\n        amount DOUBLE,\n        customer_id STRING,\n        location STRING,\n        fraud_reason STRING\n    )\n    STORED AS PARQUET\n    LOCATION \'/data/fraud_detections\';\n    INSERT INTO TABLE fraud_detections\n    SELECT\n        t.transaction_id,\n        t.date_time,\n        t.amount,\n        t.customer_id,\n        t.location,\n        \'High Amount\' AS fraud_reason\n    FROM transactions t\n    WHERE t.batch_id = \'batch_0\'\n    AND t.amount > 1000;"\n    ']
[2025-03-19T22:52:52.935+0000] {subprocess.py:86} INFO - Output:
[2025-03-19T22:52:54.293+0000] {subprocess.py:93} INFO - SLF4J: Class path contains multiple SLF4J bindings.
[2025-03-19T22:52:54.294+0000] {subprocess.py:93} INFO - SLF4J: Found binding in [jar:file:/opt/hive/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[2025-03-19T22:52:54.295+0000] {subprocess.py:93} INFO - SLF4J: Found binding in [jar:file:/opt/hadoop/share/hadoop/common/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[2025-03-19T22:52:54.296+0000] {subprocess.py:93} INFO - SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
[2025-03-19T22:52:54.470+0000] {subprocess.py:93} INFO - SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
[2025-03-19T22:52:55.744+0000] {subprocess.py:93} INFO - Connecting to jdbc:hive2://localhost:10000
[2025-03-19T22:52:56.040+0000] {subprocess.py:93} INFO - Connected to: Apache Hive (version 3.1.3)
[2025-03-19T22:52:56.041+0000] {subprocess.py:93} INFO - Driver: Hive JDBC (version 3.1.3)
[2025-03-19T22:52:56.042+0000] {subprocess.py:93} INFO - Transaction isolation: TRANSACTION_REPEATABLE_READ
[2025-03-19T22:52:56.372+0000] {subprocess.py:93} INFO - INFO  : Compiling command(queryId=root_20250319225256_d1cff924-2a36-4b70-ba99-f009dcb9aa84): CREATE TABLE IF NOT EXISTS fraud_detections (
[2025-03-19T22:52:56.373+0000] {subprocess.py:93} INFO -         transaction_id STRING,
[2025-03-19T22:52:56.374+0000] {subprocess.py:93} INFO -         date_time STRING,
[2025-03-19T22:52:56.375+0000] {subprocess.py:93} INFO -         amount DOUBLE,
[2025-03-19T22:52:56.377+0000] {subprocess.py:93} INFO -         customer_id STRING,
[2025-03-19T22:52:56.378+0000] {subprocess.py:93} INFO -         location STRING,
[2025-03-19T22:52:56.378+0000] {subprocess.py:93} INFO -         fraud_reason STRING
[2025-03-19T22:52:56.379+0000] {subprocess.py:93} INFO -     )
[2025-03-19T22:52:56.379+0000] {subprocess.py:93} INFO -     STORED AS PARQUET
[2025-03-19T22:52:56.380+0000] {subprocess.py:93} INFO -     LOCATION '/data/fraud_detections'
[2025-03-19T22:52:56.381+0000] {subprocess.py:93} INFO - INFO  : Concurrency mode is disabled, not creating a lock manager
[2025-03-19T22:52:56.381+0000] {subprocess.py:93} INFO - INFO  : Semantic Analysis Completed (retrial = false)
[2025-03-19T22:52:56.382+0000] {subprocess.py:93} INFO - INFO  : Returning Hive schema: Schema(fieldSchemas:null, properties:null)
[2025-03-19T22:52:56.382+0000] {subprocess.py:93} INFO - INFO  : Completed compiling command(queryId=root_20250319225256_d1cff924-2a36-4b70-ba99-f009dcb9aa84); Time taken: 0.007 seconds
[2025-03-19T22:52:56.383+0000] {subprocess.py:93} INFO - INFO  : Concurrency mode is disabled, not creating a lock manager
[2025-03-19T22:52:56.383+0000] {subprocess.py:93} INFO - INFO  : Executing command(queryId=root_20250319225256_d1cff924-2a36-4b70-ba99-f009dcb9aa84): CREATE TABLE IF NOT EXISTS fraud_detections (
[2025-03-19T22:52:56.383+0000] {subprocess.py:93} INFO -         transaction_id STRING,
[2025-03-19T22:52:56.384+0000] {subprocess.py:93} INFO -         date_time STRING,
[2025-03-19T22:52:56.384+0000] {subprocess.py:93} INFO -         amount DOUBLE,
[2025-03-19T22:52:56.385+0000] {subprocess.py:93} INFO -         customer_id STRING,
[2025-03-19T22:52:56.385+0000] {subprocess.py:93} INFO -         location STRING,
[2025-03-19T22:52:56.385+0000] {subprocess.py:93} INFO -         fraud_reason STRING
[2025-03-19T22:52:56.386+0000] {subprocess.py:93} INFO -     )
[2025-03-19T22:52:56.386+0000] {subprocess.py:93} INFO -     STORED AS PARQUET
[2025-03-19T22:52:56.387+0000] {subprocess.py:93} INFO -     LOCATION '/data/fraud_detections'
[2025-03-19T22:52:56.388+0000] {subprocess.py:93} INFO - INFO  : Starting task [Stage-0:DDL] in serial mode
[2025-03-19T22:52:56.388+0000] {subprocess.py:93} INFO - INFO  : Completed executing command(queryId=root_20250319225256_d1cff924-2a36-4b70-ba99-f009dcb9aa84); Time taken: 0.232 seconds
[2025-03-19T22:52:56.389+0000] {subprocess.py:93} INFO - INFO  : OK
[2025-03-19T22:52:56.389+0000] {subprocess.py:93} INFO - INFO  : Concurrency mode is disabled, not creating a lock manager
[2025-03-19T22:52:56.390+0000] {subprocess.py:93} INFO - No rows affected (0.318 seconds)
[2025-03-19T22:52:58.350+0000] {subprocess.py:93} INFO - INFO  : Compiling command(queryId=root_20250319225256_e39c6227-5c95-466f-8b77-e19c50536baa): INSERT INTO TABLE fraud_detections
[2025-03-19T22:52:58.351+0000] {subprocess.py:93} INFO -     SELECT
[2025-03-19T22:52:58.353+0000] {subprocess.py:93} INFO -         t.transaction_id,
[2025-03-19T22:52:58.354+0000] {subprocess.py:93} INFO -         t.date_time,
[2025-03-19T22:52:58.354+0000] {subprocess.py:93} INFO -         t.amount,
[2025-03-19T22:52:58.355+0000] {subprocess.py:93} INFO -         t.customer_id,
[2025-03-19T22:52:58.357+0000] {subprocess.py:93} INFO -         t.location,
[2025-03-19T22:52:58.358+0000] {subprocess.py:93} INFO -         'High Amount' AS fraud_reason
[2025-03-19T22:52:58.359+0000] {subprocess.py:93} INFO -     FROM transactions t
[2025-03-19T22:52:58.360+0000] {subprocess.py:93} INFO -     WHERE t.batch_id = 'batch_0'
[2025-03-19T22:52:58.361+0000] {subprocess.py:93} INFO -     AND t.amount > 1000
[2025-03-19T22:52:58.361+0000] {subprocess.py:93} INFO - INFO  : Concurrency mode is disabled, not creating a lock manager
[2025-03-19T22:52:58.362+0000] {subprocess.py:93} INFO - INFO  : Semantic Analysis Completed (retrial = false)
[2025-03-19T22:52:58.362+0000] {subprocess.py:93} INFO - INFO  : Returning Hive schema: Schema(fieldSchemas:[FieldSchema(name:t.transaction_id, type:string, comment:null), FieldSchema(name:t.date_time, type:string, comment:null), FieldSchema(name:t.amount, type:double, comment:null), FieldSchema(name:t.customer_id, type:string, comment:null), FieldSchema(name:t.location, type:string, comment:null), FieldSchema(name:fraud_reason, type:string, comment:null)], properties:null)
[2025-03-19T22:52:58.363+0000] {subprocess.py:93} INFO - INFO  : Completed compiling command(queryId=root_20250319225256_e39c6227-5c95-466f-8b77-e19c50536baa); Time taken: 1.438 seconds
[2025-03-19T22:52:58.364+0000] {subprocess.py:93} INFO - INFO  : Concurrency mode is disabled, not creating a lock manager
[2025-03-19T22:52:58.365+0000] {subprocess.py:93} INFO - INFO  : Executing command(queryId=root_20250319225256_e39c6227-5c95-466f-8b77-e19c50536baa): INSERT INTO TABLE fraud_detections
[2025-03-19T22:52:58.365+0000] {subprocess.py:93} INFO -     SELECT
[2025-03-19T22:52:58.366+0000] {subprocess.py:93} INFO -         t.transaction_id,
[2025-03-19T22:52:58.367+0000] {subprocess.py:93} INFO -         t.date_time,
[2025-03-19T22:52:58.367+0000] {subprocess.py:93} INFO -         t.amount,
[2025-03-19T22:52:58.368+0000] {subprocess.py:93} INFO -         t.customer_id,
[2025-03-19T22:52:58.369+0000] {subprocess.py:93} INFO -         t.location,
[2025-03-19T22:52:58.369+0000] {subprocess.py:93} INFO -         'High Amount' AS fraud_reason
[2025-03-19T22:52:58.370+0000] {subprocess.py:93} INFO -     FROM transactions t
[2025-03-19T22:52:58.370+0000] {subprocess.py:93} INFO -     WHERE t.batch_id = 'batch_0'
[2025-03-19T22:52:58.371+0000] {subprocess.py:93} INFO -     AND t.amount > 1000
[2025-03-19T22:52:58.372+0000] {subprocess.py:93} INFO - WARN  : Hive-on-MR is deprecated in Hive 2 and may not be available in the future versions. Consider using a different execution engine (i.e. spark, tez) or using Hive 1.X releases.
[2025-03-19T22:52:58.372+0000] {subprocess.py:93} INFO - INFO  : Query ID = root_20250319225256_e39c6227-5c95-466f-8b77-e19c50536baa
[2025-03-19T22:52:58.373+0000] {subprocess.py:93} INFO - INFO  : Total jobs = 3
[2025-03-19T22:52:58.373+0000] {subprocess.py:93} INFO - INFO  : Launching Job 1 out of 3
[2025-03-19T22:52:58.374+0000] {subprocess.py:93} INFO - INFO  : Starting task [Stage-1:MAPRED] in serial mode
[2025-03-19T22:52:58.375+0000] {subprocess.py:93} INFO - INFO  : Number of reduce tasks determined at compile time: 1
[2025-03-19T22:52:58.375+0000] {subprocess.py:93} INFO - INFO  : In order to change the average load for a reducer (in bytes):
[2025-03-19T22:52:58.376+0000] {subprocess.py:93} INFO - INFO  :   set hive.exec.reducers.bytes.per.reducer=<number>
[2025-03-19T22:52:58.377+0000] {subprocess.py:93} INFO - INFO  : In order to limit the maximum number of reducers:
[2025-03-19T22:52:58.378+0000] {subprocess.py:93} INFO - INFO  :   set hive.exec.reducers.max=<number>
[2025-03-19T22:52:58.378+0000] {subprocess.py:93} INFO - INFO  : In order to set a constant number of reducers:
[2025-03-19T22:52:58.379+0000] {subprocess.py:93} INFO - INFO  :   set mapreduce.job.reduces=<number>
[2025-03-19T23:10:49.423+0000] {subprocess.py:93} INFO - ERROR : Job Submission failed with exception 'java.net.ConnectException(Call From bd8f9910b295/172.18.0.2 to localhost:8032 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused)'
[2025-03-19T23:10:49.682+0000] {subprocess.py:93} INFO - java.net.ConnectException: Call From bd8f9910b295/172.18.0.2 to localhost:8032 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
[2025-03-19T23:10:49.692+0000] {subprocess.py:93} INFO - 	at sun.reflect.GeneratedConstructorAccessor96.newInstance(Unknown Source)
[2025-03-19T23:10:49.703+0000] {subprocess.py:93} INFO - 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-03-19T23:10:49.708+0000] {subprocess.py:93} INFO - 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[2025-03-19T23:10:49.710+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:831)
[2025-03-19T23:10:49.716+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:755)
[2025-03-19T23:10:49.719+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1495)
[2025-03-19T23:10:49.721+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1437)
[2025-03-19T23:10:49.728+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1347)
[2025-03-19T23:10:49.731+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:228)
[2025-03-19T23:10:49.735+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116)
[2025-03-19T23:10:49.739+0000] {subprocess.py:93} INFO - 	at com.sun.proxy.$Proxy90.getNewApplication(Unknown Source)
[2025-03-19T23:10:49.741+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.yarn.api.impl.pb.client.ApplicationClientProtocolPBClientImpl.getNewApplication(ApplicationClientProtocolPBClientImpl.java:274)
[2025-03-19T23:10:49.743+0000] {subprocess.py:93} INFO - 	at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
[2025-03-19T23:10:49.745+0000] {subprocess.py:93} INFO - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-03-19T23:10:49.746+0000] {subprocess.py:93} INFO - 	at java.lang.reflect.Method.invoke(Method.java:498)
[2025-03-19T23:10:49.747+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-03-19T23:10:49.749+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-03-19T23:10:49.757+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-03-19T23:10:49.760+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-03-19T23:10:49.762+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-03-19T23:10:49.763+0000] {subprocess.py:93} INFO - 	at com.sun.proxy.$Proxy91.getNewApplication(Unknown Source)
[2025-03-19T23:10:49.764+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.getNewApplication(YarnClientImpl.java:252)
[2025-03-19T23:10:49.766+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.createApplication(YarnClientImpl.java:260)
[2025-03-19T23:10:49.776+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.ResourceMgrDelegate.getNewJobID(ResourceMgrDelegate.java:196)
[2025-03-19T23:10:49.780+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.YARNRunner.getNewJobID(YARNRunner.java:271)
[2025-03-19T23:10:49.782+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:160)
[2025-03-19T23:10:49.792+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapreduce.Job$11.run(Job.java:1570)
[2025-03-19T23:10:49.794+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapreduce.Job$11.run(Job.java:1567)
[2025-03-19T23:10:49.796+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-03-19T23:10:49.797+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-03-19T23:10:49.798+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1682)
[2025-03-19T23:10:49.801+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapreduce.Job.submit(Job.java:1567)
[2025-03-19T23:10:49.806+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.JobClient$1.run(JobClient.java:576)
[2025-03-19T23:10:49.853+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.JobClient$1.run(JobClient.java:571)
[2025-03-19T23:10:49.904+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-03-19T23:10:49.926+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-03-19T23:10:49.933+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1682)
[2025-03-19T23:10:49.937+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.JobClient.submitJobInternal(JobClient.java:571)
[2025-03-19T23:10:49.939+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.JobClient.submitJob(JobClient.java:562)
[2025-03-19T23:10:49.940+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hive.ql.exec.mr.ExecDriver.execute(ExecDriver.java:423)
[2025-03-19T23:10:49.941+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hive.ql.exec.mr.MapRedTask.execute(MapRedTask.java:149)
[2025-03-19T23:10:49.942+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:205)
[2025-03-19T23:10:49.943+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:97)
[2025-03-19T23:10:49.944+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hive.ql.Driver.launchTask(Driver.java:2664)
[2025-03-19T23:10:49.944+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:2335)
[2025-03-19T23:10:49.945+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:2011)
[2025-03-19T23:10:49.946+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1709)
[2025-03-19T23:10:49.948+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:1703)
[2025-03-19T23:10:49.949+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hive.ql.reexec.ReExecDriver.run(ReExecDriver.java:157)
[2025-03-19T23:10:49.950+0000] {subprocess.py:93} INFO - 	at org.apache.hive.service.cli.operation.SQLOperation.runQuery(SQLOperation.java:224)
[2025-03-19T23:10:49.950+0000] {subprocess.py:93} INFO - 	at org.apache.hive.service.cli.operation.SQLOperation.access$700(SQLOperation.java:87)
[2025-03-19T23:10:49.951+0000] {subprocess.py:93} INFO - 	at org.apache.hive.service.cli.operation.SQLOperation$BackgroundWork$1.run(SQLOperation.java:316)
[2025-03-19T23:10:49.952+0000] {subprocess.py:93} INFO - 	at java.security.AccessController.doPrivileged(Native Method)
[2025-03-19T23:10:49.953+0000] {subprocess.py:93} INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
[2025-03-19T23:10:49.953+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1682)
[2025-03-19T23:10:49.954+0000] {subprocess.py:93} INFO - 	at org.apache.hive.service.cli.operation.SQLOperation$BackgroundWork.run(SQLOperation.java:329)
[2025-03-19T23:10:49.955+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2025-03-19T23:10:49.956+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2025-03-19T23:10:49.958+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2025-03-19T23:10:49.962+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2025-03-19T23:10:49.964+0000] {subprocess.py:93} INFO - 	at java.lang.Thread.run(Thread.java:750)
[2025-03-19T23:10:49.966+0000] {subprocess.py:93} INFO - Caused by: java.net.ConnectException: Connection refused
[2025-03-19T23:10:49.969+0000] {subprocess.py:93} INFO - 	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
[2025-03-19T23:10:49.970+0000] {subprocess.py:93} INFO - 	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
[2025-03-19T23:10:49.971+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
[2025-03-19T23:10:49.973+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:531)
[2025-03-19T23:10:49.974+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:685)
[2025-03-19T23:10:49.975+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:788)
[2025-03-19T23:10:49.976+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.access$3500(Client.java:409)
[2025-03-19T23:10:49.976+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1552)
[2025-03-19T23:10:49.977+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1383)
[2025-03-19T23:10:49.978+0000] {subprocess.py:93} INFO - 	... 54 more
[2025-03-19T23:10:49.979+0000] {subprocess.py:93} INFO - 
[2025-03-19T23:10:49.979+0000] {subprocess.py:93} INFO - ERROR : FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask. Call From bd8f9910b295/172.18.0.2 to localhost:8032 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
[2025-03-19T23:10:49.980+0000] {subprocess.py:93} INFO - INFO  : Completed executing command(queryId=root_20250319225256_e39c6227-5c95-466f-8b77-e19c50536baa); Time taken: 1071.457 seconds
[2025-03-19T23:10:49.981+0000] {subprocess.py:93} INFO - INFO  : Concurrency mode is disabled, not creating a lock manager
[2025-03-19T23:10:49.982+0000] {subprocess.py:93} INFO - Error: Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask. Call From bd8f9910b295/172.18.0.2 to localhost:8032 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused (state=08S01,code=1)
[2025-03-19T23:10:50.181+0000] {subprocess.py:93} INFO - Closing: 0: jdbc:hive2://localhost:10000
[2025-03-19T23:10:50.479+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-03-19T23:10:50.661+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-19T23:10:50.701+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=transactions_pipeline, task_id=detect_fraud, execution_date=20250319T225231, start_date=20250319T225252, end_date=20250319T231050
[2025-03-19T23:10:50.795+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 211 for task detect_fraud (Bash command failed. The command returned a non-zero exit code 1.; 249)
[2025-03-19T23:10:50.878+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-19T23:10:51.004+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
